# Generated by Django 4.2.3 on 2023-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communication',
                'db_table': 'communication',
            },
        ),
    ]
