# Generated by Django 4.2.3 on 2023-07-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_communicationmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postmodel',
            table=None,
        ),
    ]
