# Generated by Django 4.2.3 on 2023-07-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_postmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
