from .contact import contact
from .main import main
from .category import category
from .myposts import myposts
from .detail import detail
from .add_post import add_post
from .update_post import update_post
from .delete_post import delete_post
from .delete_comment import delete_comment